---    
- name: Log in as deploy user and setup ruby, passenger and nginx
  hosts: localhost
  connection: local 
  vars_files:
    - config
    - packages.yml
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
  user: "{{ macbook_user }}"
  become: true
  become_user: "{{ macbook_user }}"
  roles: 
    - role: macbook
      tags: macbook
    - geerlingguy.homebrew
    - role: gantsign.visual-studio-code-extensions
      users:
        - username: picfair
          visual_studio_code_extensions:
            - abalejr.forest-focus
            - aregghazaryan.glass-ui
            - dbaeumer.vscode-eslint
            - gerane.Theme-zombiesatemyneighbors
            - johnpapa.vscode-peacock
            - jpoissonnier.vscode-styled-components
            - juhakokkonen.py-light
            - karunamurti.haml
            - kumar-harsh.graphql-for-vscode
            - lintangwisesa.arduino
            - lninl.theme-hbuilderx-soft-green-light
            - luqimin.tiny-light
            - misogi.ruby-rubocop
            - raashida.fixthecode-vs
            - rebornix.ruby
            - selfrefactor.zeppelin-themes
            - sveggiani.vscode-field-lights
            - syler.sass-indented
            - taniarascia.new-moon-vscode
            - teabyii.ayu
            - tristanremy.mirage
            - wingrunr21.vscode-ruby
            - wraith13.unsaved-files-vscode
